### ISSUE TITLE
r is not defined

### ISSUE THREAD

**Issue by bknill** [morandd/aframe-multitouch-look-controls#2]
I'm using this on the camera entity, however getting this compile error:

Line 129:  'r' is not defined     no-undef

Used on this `<Entity primitive='a-camera' id='camera' multitouch-look-controls mouse-cursor mouse-zoom wasd-controls={wasdControls} stereocam="eye:left">`

Is this a different type of camera?

**Comment by Valink** [comment]
This error come from your typescript compiling configuration.
But this repo is broken, import this file instead : 
https://raw.githubusercontent.com/morandd/aframe-multitouch-look-controls/master/multitouch-look-controls.js
And add "r" declaration arround line 127 : "var **r**, r1, r2;"

**Comment by jlecordier** [comment]
@morandd You can close this issue, il has been resolved by my PR
